// ─── Warehouses ───────────────────────────────────────────────────────────────
export const warehouses = [
  { id: "w1", name: "Warehouse A", lat: 23.8103, lng: 90.4125, managerId: "u2" },
  { id: "w2", name: "Warehouse B", lat: 23.7500, lng: 90.3800, managerId: "u5" },
  { id: "w3", name: "Warehouse C", lat: 23.8200, lng: 90.4500, managerId: "u10" },
  { id: "w4", name: "Warehouse D", lat: 23.7000, lng: 90.3500, managerId: "u2" },
  { id: "w5", name: "Warehouse E", lat: 23.7800, lng: 90.5000, managerId: "u10" },
];

// ─── Users ────────────────────────────────────────────────────────────────────
export const users = [
  {
    id: "u1",
    name: "Rahim Uddin",
    username: "rahim",
    role: "central_admin",
    team: "HQ Operations",
    teamId: "t6",
    phone: "+880-1711-234567",
    status: "Active",
    lastLogin: "2026-07-26T10:15:00Z",
  },
  {
    id: "u2",
    name: "Fatima Begum",
    username: "fatima",
    role: "warehouse_manager",
    team: "Logistics Unit",
    teamId: "t7",
    phone: "+880-1812-345678",
    status: "Active",
    lastLogin: "2026-07-26T09:45:00Z",
  },
  {
    id: "u3",
    name: "Kamal Hossain",
    username: "kamal",
    role: "field_worker",
    team: "Sylhet Flood Response",
    teamId: "t1",
    phone: "+880-1913-456789",
    status: "Active",
    lastLogin: "2026-07-26T08:30:00Z",
  },
  {
    id: "u4",
    name: "Nasrin Akter",
    username: "nasrin",
    role: "field_worker",
    team: "Barishal Cyclone Relief",
    teamId: "t2",
    phone: "+880-1614-567890",
    status: "Active",
    lastLogin: "2026-07-26T07:20:00Z",
  },
  {
    id: "u5",
    name: "Mizanur Rahman",
    username: "mizanur",
    role: "warehouse_manager",
    team: "Logistics Unit",
    teamId: "t7",
    phone: "+880-1515-678901",
    status: "Inactive",
    lastLogin: "2026-07-20T14:00:00Z",
  },
  {
    id: "u6",
    name: "Taslima Khatun",
    username: "taslima",
    role: "field_worker",
    team: "Khulna Emergency Squad",
    teamId: "t3",
    phone: "+880-1716-789012",
    status: "Active",
    lastLogin: "2026-07-26T11:10:00Z",
  },
  {
    id: "u7",
    name: "Jahangir Alam",
    username: "jahangir",
    role: "field_worker",
    team: "Rangpur Earthquake Aid",
    teamId: "t4",
    phone: "+880-1817-890123",
    status: "Offline",
    lastLogin: "2026-07-25T22:45:00Z",
  },
  {
    id: "u8",
    name: "Sharmin Sultana",
    username: "sharmin",
    role: "central_admin",
    team: "HQ Operations",
    teamId: "t6",
    phone: "+880-1918-901234",
    status: "Active",
    lastLogin: "2026-07-26T10:50:00Z",
  },
  {
    id: "u9",
    name: "Abdul Kader",
    username: "abdul",
    role: "field_worker",
    team: "Cumilla Fire Response",
    teamId: "t5",
    phone: "+880-1619-012345",
    status: "Active",
    lastLogin: "2026-07-26T06:30:00Z",
  },
  {
    id: "u10",
    name: "Roksana Parvin",
    username: "roksana",
    role: "warehouse_manager",
    team: "Logistics Unit",
    teamId: "t7",
    phone: "+880-1510-123456",
    status: "Active",
    lastLogin: "2026-07-26T09:00:00Z",
  },
];

// ─── Teams ────────────────────────────────────────────────────────────────────
export const teams = [
  {
    id: "t1",
    name: "Sylhet Flood Response",
    leader: "Kamal Hossain",
    leaderId: "u3",
    memberCount: 12,
    status: "Deployed",
    location: "Sylhet",
    locationCoords: { lat: 24.8949, lng: 91.8687 },
    activeTask: "Distribute emergency food packets to marooned villages",
    activeTaskId: "task1",
  },
  {
    id: "t2",
    name: "Barishal Cyclone Relief",
    leader: "Nasrin Akter",
    leaderId: "u4",
    memberCount: 8,
    status: "Deployed",
    location: "Barishal",
    locationCoords: { lat: 22.701, lng: 90.3535 },
    activeTask: "Set up temporary shelters in coastal areas",
    activeTaskId: "task2",
  },
  {
    id: "t3",
    name: "Khulna Emergency Squad",
    leader: "Taslima Khatun",
    leaderId: "u6",
    memberCount: 10,
    status: "Standby",
    location: "Khulna",
    locationCoords: { lat: 22.8456, lng: 89.5403 },
    activeTask: "Awaiting deployment orders for Sundarbans region",
    activeTaskId: "task3",
  },
  {
    id: "t4",
    name: "Rangpur Earthquake Aid",
    leader: "Jahangir Alam",
    leaderId: "u7",
    memberCount: 6,
    status: "Offline",
    location: "Rangpur",
    locationCoords: { lat: 25.7439, lng: 89.2752 },
    activeTask: "Post-earthquake structural damage assessment",
    activeTaskId: "task5",
  },
  {
    id: "t5",
    name: "Cumilla Fire Response",
    leader: "Abdul Kader",
    leaderId: "u9",
    memberCount: 9,
    status: "Deployed",
    location: "Cumilla",
    locationCoords: { lat: 23.4607, lng: 91.1809 },
    activeTask: "Provide medical aid to burn victims in market area",
    activeTaskId: "task4",
  },
  {
    id: "t6",
    name: "HQ Operations",
    leader: "Rahim Uddin",
    leaderId: "u1",
    memberCount: 2,
    status: "Deployed",
    location: "Dhaka",
    locationCoords: { lat: 23.8103, lng: 90.4125 },
    activeTask: "Coordinate nationwide response and resource allocation",
    activeTaskId: null,
  },
  {
    id: "t7",
    name: "Logistics Unit",
    leader: "Fatima Begum",
    leaderId: "u2",
    memberCount: 3,
    status: "Standby",
    location: "Dhaka",
    locationCoords: { lat: 23.8103, lng: 90.4125 },
    activeTask: "Manage warehouse stock and dispatch supplies",
    activeTaskId: null,
  },
];

// ─── Reports ──────────────────────────────────────────────────────────────────
export const reports = [
  {
    id: "r1",
    type: "Flood",
    district: "Sylhet",
    location: { lat: 24.8949, lng: 91.8687 },
    severity: 5,
    status: "Acknowledged",
    submittedBy: "Kamal Hossain",
    submittedById: "u3",
    time: "2026-07-25T14:30:00Z",
    description:
      "Severe flash flood in Sylhet's Companiganj upazila. Multiple villages submerged, roads impassable. Immediate evacuation required for 3 riverside communities.",
    affectedCount: 4500,
    urgencyScore: 95,
    childrenPresent: true,
    elderlyPresent: true,
  },
  {
    id: "r2",
    type: "Cyclone",
    district: "Barishal",
    location: { lat: 22.701, lng: 90.3535 },
    severity: 4,
    status: "Pending",
    submittedBy: "Nasrin Akter",
    submittedById: "u4",
    time: "2026-07-26T02:15:00Z",
    description:
      "Cyclone warning issued for Barishal coast. Wind speeds exceeding 120 km/h expected. Coastal embankments at risk of breach. Pre-emptive shelter activation needed.",
    affectedCount: 12000,
    urgencyScore: 88,
    childrenPresent: true,
    elderlyPresent: true,
  },
  {
    id: "r3",
    type: "Earthquake",
    district: "Rangpur",
    location: { lat: 25.7439, lng: 89.2752 },
    severity: 3,
    status: "Resolved",
    submittedBy: "Jahangir Alam",
    submittedById: "u7",
    time: "2026-07-20T06:45:00Z",
    description:
      "Moderate earthquake (4.2 magnitude) near Rangpur town. Several mud-brick structures collapsed in rural areas. No major casualties reported.",
    affectedCount: 800,
    urgencyScore: 42,
    childrenPresent: false,
    elderlyPresent: true,
  },
  {
    id: "r4",
    type: "Fire",
    district: "Cumilla",
    location: { lat: 23.4607, lng: 91.1809 },
    severity: 4,
    status: "Acknowledged",
    submittedBy: "Abdul Kader",
    submittedById: "u9",
    time: "2026-07-24T19:00:00Z",
    description:
      "Major fire broke out in Cumilla's central market area. Over 50 shops destroyed. Several residential buildings affected. Burn victims require medical attention.",
    affectedCount: 320,
    urgencyScore: 76,
    childrenPresent: true,
    elderlyPresent: false,
  },
  {
    id: "r5",
    type: "Flood",
    district: "Mymensingh",
    location: { lat: 24.7471, lng: 90.4203 },
    severity: 4,
    status: "Pending",
    submittedBy: "Kamal Hossain",
    submittedById: "u3",
    time: "2026-07-26T08:00:00Z",
    description:
      "Brahmaputra river breached embankment near Mymensingh Sadar. Low-lying areas flooding rapidly. Agricultural land submerged across 3 unions.",
    affectedCount: 6200,
    urgencyScore: 82,
    childrenPresent: true,
    elderlyPresent: true,
  },
  {
    id: "r6",
    type: "Cyclone",
    district: "Chattogram",
    location: { lat: 22.3569, lng: 91.7832 },
    severity: 5,
    status: "Pending",
    submittedBy: "Nasrin Akter",
    submittedById: "u4",
    time: "2026-07-26T05:30:00Z",
    description:
      "Super cyclone making landfall near Chattogram port. Massive storm surge expected. All port operations halted. Over 50,000 people in vulnerable zones.",
    affectedCount: 52000,
    urgencyScore: 98,
    childrenPresent: true,
    elderlyPresent: true,
  },
  {
    id: "r7",
    type: "Other",
    district: "Dhaka",
    location: { lat: 23.8103, lng: 90.4125 },
    severity: 2,
    status: "Resolved",
    submittedBy: "Rahim Uddin",
    submittedById: "u1",
    time: "2026-07-22T11:00:00Z",
    description:
      "Building collapse in old Dhaka due to structural weakness. Emergency teams extracted all residents safely. Area cordoned off for safety inspection.",
    affectedCount: 45,
    urgencyScore: 30,
    childrenPresent: false,
    elderlyPresent: true,
  },
  {
    id: "r8",
    type: "Flood",
    district: "Noakhali",
    location: { lat: 22.8696, lng: 91.0995 },
    severity: 3,
    status: "Acknowledged",
    submittedBy: "Taslima Khatun",
    submittedById: "u6",
    time: "2026-07-25T16:45:00Z",
    description:
      "Tidal surge caused waterlogging in Noakhali's Hatiya island. Freshwater sources contaminated. Drinking water supply urgently needed for island communities.",
    affectedCount: 2100,
    urgencyScore: 65,
    childrenPresent: true,
    elderlyPresent: false,
  },
  {
    id: "r9",
    type: "Fire",
    district: "Rajshahi",
    location: { lat: 24.3745, lng: 88.6042 },
    severity: 1,
    status: "Pending",
    submittedBy: "Abdul Kader",
    submittedById: "u9",
    time: "2026-07-21T13:20:00Z",
    description:
      "Small fire in a Rajshahi jute warehouse. Fire service responded quickly. Minimal structural damage. Workers evacuated safely before fire spread.",
    affectedCount: 15,
    urgencyScore: 22,
    childrenPresent: false,
    elderlyPresent: false,
  },
  {
    id: "r10",
    type: "Flood",
    district: "Khulna",
    location: { lat: 22.8456, lng: 89.5403 },
    severity: 3,
    status: "Pending",
    submittedBy: "Taslima Khatun",
    submittedById: "u6",
    time: "2026-07-26T10:00:00Z",
    description:
      "Rising water levels in Rupsa River threatening Khulna city's southern wards. Slum areas at high risk. Pre-emptive evacuation recommended for 1,500 families.",
    affectedCount: 7500,
    urgencyScore: 70,
    childrenPresent: true,
    elderlyPresent: true,
  },
];

// ─── Inventory ────────────────────────────────────────────────────────────────
export const inventory = [
  {
    id: "inv1",
    name: "Rice (Fortified)",
    category: "Food",
    qty: 2500,
    unit: "kg",
    warehouse: "Warehouse A",
    warehouseId: "w1",
    lastUpdated: "2026-07-26T08:00:00Z",
    status: "OK",
  },
  {
    id: "inv2",
    name: "Oral Rehydration Salts",
    category: "Medicine",
    qty: 300,
    unit: "boxes",
    warehouse: "Warehouse B",
    warehouseId: "w2",
    lastUpdated: "2026-07-25T14:30:00Z",
    status: "OK",
  },
  {
    id: "inv3",
    name: "Emergency Tarpaulins",
    category: "Shelter",
    qty: 8,
    unit: "units",
    warehouse: "Warehouse A",
    warehouseId: "w1",
    lastUpdated: "2026-07-26T06:00:00Z",
    status: "Low",
  },
  {
    id: "inv4",
    name: "Water Purification Tablets",
    category: "Medicine",
    qty: 5,
    unit: "boxes",
    warehouse: "Warehouse C",
    warehouseId: "w3",
    lastUpdated: "2026-07-26T09:15:00Z",
    status: "Critical",
  },
  {
    id: "inv5",
    name: "Portable Water Pumps",
    category: "Equipment",
    qty: 15,
    unit: "units",
    warehouse: "Warehouse D",
    warehouseId: "w4",
    lastUpdated: "2026-07-24T17:00:00Z",
    status: "OK",
  },
  {
    id: "inv6",
    name: "First Aid Kits",
    category: "Medicine",
    qty: 7,
    unit: "boxes",
    warehouse: "Warehouse B",
    warehouseId: "w2",
    lastUpdated: "2026-07-25T11:00:00Z",
    status: "Low",
  },
  {
    id: "inv7",
    name: "Tents (Family-size)",
    category: "Shelter",
    qty: 45,
    unit: "units",
    warehouse: "Warehouse A",
    warehouseId: "w1",
    lastUpdated: "2026-07-23T10:00:00Z",
    status: "OK",
  },
  {
    id: "inv8",
    name: "Dry Biscuits",
    category: "Food",
    qty: 1200,
    unit: "boxes",
    warehouse: "Warehouse C",
    warehouseId: "w3",
    lastUpdated: "2026-07-26T07:30:00Z",
    status: "OK",
  },
  {
    id: "inv9",
    name: "Flashlights & Batteries",
    category: "Equipment",
    qty: 3,
    unit: "boxes",
    warehouse: "Warehouse E",
    warehouseId: "w5",
    lastUpdated: "2026-07-26T10:00:00Z",
    status: "Critical",
  },
  {
    id: "inv10",
    name: "Saline Drip Sets",
    category: "Medicine",
    qty: 80,
    unit: "units",
    warehouse: "Warehouse B",
    warehouseId: "w2",
    lastUpdated: "2026-07-25T09:00:00Z",
    status: "OK",
  },
  {
    id: "inv11",
    name: "Blankets (Thermal)",
    category: "Shelter",
    qty: 200,
    unit: "units",
    warehouse: "Warehouse D",
    warehouseId: "w4",
    lastUpdated: "2026-07-22T16:00:00Z",
    status: "OK",
  },
  {
    id: "inv12",
    name: "Cooking Oil",
    category: "Food",
    qty: 6,
    unit: "liters",
    warehouse: "Warehouse C",
    warehouseId: "w3",
    lastUpdated: "2026-07-26T08:45:00Z",
    status: "Low",
  },
  {
    id: "inv13",
    name: "Stretchers (Foldable)",
    category: "Equipment",
    qty: 20,
    unit: "units",
    warehouse: "Warehouse A",
    warehouseId: "w1",
    lastUpdated: "2026-07-21T12:00:00Z",
    status: "OK",
  },
  {
    id: "inv14",
    name: "Chlorine Solution",
    category: "Medicine",
    qty: 50,
    unit: "liters",
    warehouse: "Warehouse E",
    warehouseId: "w5",
    lastUpdated: "2026-07-24T15:00:00Z",
    status: "OK",
  },
  {
    id: "inv15",
    name: "Rope & Rescue Harness",
    category: "Equipment",
    qty: 4,
    unit: "units",
    warehouse: "Warehouse D",
    warehouseId: "w4",
    lastUpdated: "2026-07-26T06:30:00Z",
    status: "Low",
  },
  {
    id: "inv16",
    name: "Flatbread (Roti Packs)",
    category: "Food",
    qty: 900,
    unit: "boxes",
    warehouse: "Warehouse A",
    warehouseId: "w1",
    lastUpdated: "2026-07-25T18:00:00Z",
    status: "OK",
  },
  {
    id: "inv17",
    name: "Plastic Sheeting Rolls",
    category: "Shelter",
    qty: 2,
    unit: "units",
    warehouse: "Warehouse E",
    warehouseId: "w5",
    lastUpdated: "2026-07-26T10:30:00Z",
    status: "Critical",
  },
  {
    id: "inv18",
    name: "Solar Lanterns",
    category: "Equipment",
    qty: 60,
    unit: "units",
    warehouse: "Warehouse C",
    warehouseId: "w3",
    lastUpdated: "2026-07-23T14:00:00Z",
    status: "OK",
  },
  {
    id: "inv19",
    name: "Paracetamol Tablets",
    category: "Medicine",
    qty: 9,
    unit: "boxes",
    warehouse: "Warehouse B",
    warehouseId: "w2",
    lastUpdated: "2026-07-26T09:45:00Z",
    status: "Low",
  },
  {
    id: "inv20",
    name: "Drinking Water (Bottled)",
    category: "Food",
    qty: 3000,
    unit: "liters",
    warehouse: "Warehouse A",
    warehouseId: "w1",
    lastUpdated: "2026-07-26T11:00:00Z",
    status: "OK",
  },
];

// ─── Tasks ────────────────────────────────────────────────────────────────────
export const tasks = [
  {
    id: "task1",
    title: "Evacuate Companiganj villages",
    description:
      "Coordinate boat evacuation for 3 riverside communities in Companiganj upazila. Prioritise women, children, and elderly.",
    priority: "Critical",
    assignedTo: "Kamal Hossain",
    assignedTeamId: "t1",
    assignedUserId: "u3",
    dueTime: "2026-07-26T14:00:00Z",
    status: "In Progress",
    linkedReport: "r1",
  },
  {
    id: "task2",
    title: "Activate coastal cyclone shelters",
    description:
      "Open and stock all 12 designated cyclone shelters along Barishal coastline before landfall.",
    priority: "Critical",
    assignedTo: "Nasrin Akter",
    assignedTeamId: "t2",
    assignedUserId: "u4",
    dueTime: "2026-07-26T18:00:00Z",
    status: "To Do",
    linkedReport: "r2",
  },
  {
    id: "task3",
    title: "Deliver water purification supplies",
    description:
      "Transport water purification tablets and chlorine solution from Warehouse C to Noakhali Hatiya island distribution point.",
    priority: "High",
    assignedTo: "Taslima Khatun",
    assignedTeamId: "t3",
    assignedUserId: "u6",
    dueTime: "2026-07-27T08:00:00Z",
    status: "En Route",
    linkedReport: "r8",
  },
  {
    id: "task4",
    title: "Medical camp setup in Cumilla",
    description:
      "Set up field medical camp near Cumilla central market for treating burn victims. Coordinate with local hospital for severe cases.",
    priority: "High",
    assignedTo: "Abdul Kader",
    assignedTeamId: "t5",
    assignedUserId: "u9",
    dueTime: "2026-07-26T16:00:00Z",
    status: "In Progress",
    linkedReport: "r4",
  },
  {
    id: "task5",
    title: "Structural assessment — Rangpur",
    description:
      "Complete damage assessment for all collapsed structures in rural Rangpur. Tag buildings as safe / unsafe for re-entry.",
    priority: "Medium",
    assignedTo: "Jahangir Alam",
    assignedTeamId: "t4",
    assignedUserId: "u7",
    dueTime: "2026-07-28T12:00:00Z",
    status: "Completed",
    linkedReport: "r3",
  },
  {
    id: "task6",
    title: "Restock Warehouse E critical items",
    description:
      "Coordinate procurement and delivery of plastic sheeting rolls, flashlights, and batteries to Warehouse E. Current stock at critical levels.",
    priority: "High",
    assignedTo: "Fatima Begum",
    assignedTeamId: "t2",
    assignedUserId: "u2",
    dueTime: "2026-07-27T10:00:00Z",
    status: "To Do",
    linkedReport: "r10",
  },
  {
    id: "task7",
    title: "Distribute food packets — Mymensingh",
    description:
      "Distribute 500 emergency food packets (rice + dry biscuits) to flood-affected families in Mymensingh Sadar unions.",
    priority: "Critical",
    assignedTo: "Kamal Hossain",
    assignedTeamId: "t1",
    assignedUserId: "u3",
    dueTime: "2026-07-26T20:00:00Z",
    status: "To Do",
    linkedReport: "r5",
  },
  {
    id: "task8",
    title: "Pre-emptive evacuation — Khulna wards",
    description:
      "Coordinate voluntary evacuation of 1,500 families from southern Khulna wards before Rupsa River levels reach danger mark.",
    priority: "Medium",
    assignedTo: "Taslima Khatun",
    assignedTeamId: "t3",
    assignedUserId: "u6",
    dueTime: "2026-07-27T06:00:00Z",
    status: "To Do",
    linkedReport: "r10",
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────
export const notifications = [
  {
    id: "n1",
    title: "Cyclone Alert — Chattogram",
    body: "Super cyclone approaching Chattogram coast. All field teams must report to nearest shelter immediately.",
    timestamp: "2026-07-26T05:35:00Z",
    read: false,
    type: "Critical",
  },
  {
    id: "n2",
    title: "Warehouse E Stock Critical",
    body: "Flashlights, batteries, and plastic sheeting at critical levels. Restock order has been initiated.",
    timestamp: "2026-07-26T10:05:00Z",
    read: false,
    type: "System",
  },
  {
    id: "n3",
    title: "Task Completed — Rangpur Assessment",
    body: "Structural damage assessment in Rangpur has been marked as completed by Jahangir Alam.",
    timestamp: "2026-07-26T09:30:00Z",
    read: true,
    type: "Info",
  },
  {
    id: "n4",
    title: "New Report Submitted",
    body: "Flood report submitted for Khulna — Rupsa River embankment under threat. Review and assign team.",
    timestamp: "2026-07-26T10:02:00Z",
    read: false,
    type: "System",
  },
  {
    id: "n5",
    title: "Medical Supplies Running Low",
    body: "First Aid Kits and Paracetamol stocks below threshold in Warehouse B. Immediate procurement recommended.",
    timestamp: "2026-07-26T09:50:00Z",
    read: true,
    type: "Critical",
  },
  {
    id: "n6",
    title: "Team Deployed — Sylhet",
    body: "Sylhet Flood Response team has been deployed to Companiganj upazila for evacuation operations.",
    timestamp: "2026-07-25T15:00:00Z",
    read: true,
    type: "Info",
  },
];

// ─── Alerts ───────────────────────────────────────────────────────────────────
export const alerts = [
  {
    id: "a1",
    severity: "Critical",
    message:
      "Super cyclone making landfall in 12 hours — Chattogram and Barishal divisions on highest alert.",
    location: "Chattogram",
    timestamp: "2026-07-26T05:30:00Z",
  },
  {
    id: "a2",
    severity: "Critical",
    message:
      "Flash flood waters rising rapidly in Sylhet — Companiganj area evacuation priority one.",
    location: "Sylhet",
    timestamp: "2026-07-25T14:35:00Z",
  },
  {
    id: "a3",
    severity: "High",
    message:
      "Brahmaputra river at danger level near Mymensingh. Embankment breach imminent in Sadar upazila.",
    location: "Mymensingh",
    timestamp: "2026-07-26T08:10:00Z",
  },
  {
    id: "a4",
    severity: "Medium",
    message:
      "Rupsa River levels approaching warning mark in Khulna. Southern wards advised to prepare for evacuation.",
    location: "Khulna",
    timestamp: "2026-07-26T10:05:00Z",
  },
  {
    id: "a5",
    severity: "High",
    message:
      "Multiple critical inventory items below threshold in Warehouse E. Supply chain disruption expected due to cyclone.",
    location: "Dhaka",
    timestamp: "2026-07-26T10:30:00Z",
  },
];

// ─── City Coordinates ─────────────────────────────────────────────────────────
export const cityCoords = {
  Sylhet: [24.8949, 91.8687],
  Barishal: [22.7010, 90.3535],
  Rangpur: [25.7439, 89.2752],
  Cumilla: [23.4607, 91.1809],
  Dhaka: [23.8103, 90.4125],
  Chattogram: [22.3569, 91.7832],
  Mymensingh: [24.7471, 90.4203],
  Noakhali: [22.8696, 91.0995],
  Khulna: [22.8456, 89.5403],
  Rajshahi: [24.3745, 88.6042],
  Mirpur: [23.8041, 90.3665],
};

// ─── Supply Drops ─────────────────────────────────────────────────────────────
export const supplyDrops = [
  {
    id: "sd1",
    location: "Sylhet",
    name: "Food & Water Drop — Companiganj",
    status: "Delivered",
    lastUpdate: "2026-07-26T08:30:00Z",
  },
  {
    id: "sd2",
    location: "Barishal",
    name: "Shelter Supplies — Coastal Zone",
    status: "En Route",
    lastUpdate: "2026-07-26T10:00:00Z",
  },
  {
    id: "sd3",
    location: "Cumilla",
    name: "Medical Supplies Drop — Central",
    status: "Delivered",
    lastUpdate: "2026-07-25T16:45:00Z",
  },
];

// ─── Peer Devices ─────────────────────────────────────────────────────────────
export const peerDevices = [
  {
    id: "pd1",
    deviceName: "Field Tablet — Kamal",
    signalStrength: "High",
    status: "Available",
    lastSeen: "2026-07-26T11:00:00Z",
  },
  {
    id: "pd2",
    deviceName: "Mobile — Nasrin",
    signalStrength: "Medium",
    status: "Available",
    lastSeen: "2026-07-26T10:55:00Z",
  },
  {
    id: "pd3",
    deviceName: "Rugged Phone — Taslima",
    signalStrength: "Low",
    status: "Busy",
    lastSeen: "2026-07-26T10:40:00Z",
  },
];

// ─── Offline Queue ────────────────────────────────────────────────────────────
export const offlineQueue = [
  {
    id: "oq1",
    actionType: "New Report",
    timestamp: "2026-07-26T11:15:00Z",
    status: "Queued",
    details: "Flood report — Mymensingh",
  },
  {
    id: "oq2",
    actionType: "Stock Update",
    timestamp: "2026-07-26T11:10:00Z",
    status: "Queued",
    details: "Rice qty updated to 2,450 kg",
  },
  {
    id: "oq3",
    actionType: "Task Update",
    timestamp: "2026-07-26T11:05:00Z",
    status: "Syncing",
    details: "Evacuation task marked in progress",
  },
  {
    id: "oq4",
    actionType: "Stock Update",
    timestamp: "2026-07-26T10:50:00Z",
    status: "Failed",
    details: "Paracetamol stock update failed",
  },
  {
    id: "oq5",
    actionType: "Task Update",
    timestamp: "2026-07-26T10:30:00Z",
    status: "Queued",
    details: "Medical camp setup completed",
  },
];

// ─── Cargo Vehicles ───────────────────────────────────────────────────────────
export const cargoVehicles = [
  {
    id: "cv1",
    name: "Relief Truck Alpha",
    length: 6.2,
    width: 2.4,
    height: 2.5,
    maxWeight: 3000,
  },
  {
    id: "cv2",
    name: "Cargo Van Bravo",
    length: 4.5,
    width: 2.0,
    height: 2.0,
    maxWeight: 1200,
  },
  {
    id: "cv3",
    name: "Heavy Hauler Charlie",
    length: 9.0,
    width: 2.6,
    height: 2.8,
    maxWeight: 8000,
  },
];

// ─── Seed Data ────────────────────────────────────────────────────────────────
// Used by src/lib/db.js to seed IndexedDB on first launch. Every store is keyed
// by "id", so every record here must carry one.
export const seedData = {
  reports,
  tasks,
  inventory,
  users,
  teams,
  warehouses: [
    { id: "w1", name: "Warehouse A" },
    { id: "w2", name: "Warehouse B" },
    { id: "w3", name: "Warehouse C" },
    { id: "w4", name: "Warehouse D" },
    { id: "w5", name: "Warehouse E" },
  ],
  notifications,
  stockLog: [
    { id: "log1", itemId: "inv20", itemName: "Drinking Water (Bottled)", change: 500, reason: "Restocking", user: "Fatima Begum", timestamp: "2026-07-26T11:10:00Z" },
    { id: "log2", itemId: "inv17", itemName: "Plastic Sheeting Rolls", change: -3, reason: "Distribution", user: "Kamal Hossain", timestamp: "2026-07-26T10:35:00Z" },
    { id: "log3", itemId: "inv9", itemName: "Flashlights & Batteries", change: -2, reason: "Damage", user: "Mizanur Rahman", timestamp: "2026-07-26T10:05:00Z" },
    { id: "log4", itemId: "inv19", itemName: "Paracetamol Tablets", change: 20, reason: "Restocking", user: "Fatima Begum", timestamp: "2026-07-26T09:45:00Z" },
    { id: "log5", itemId: "inv12", itemName: "Cooking Oil", change: -4, reason: "Distribution", user: "Nasrin Akter", timestamp: "2026-07-26T08:50:00Z" },
    { id: "log6", itemId: "inv1", itemName: "Rice (Fortified)", change: -120, reason: "Distribution", user: "Kamal Hossain", timestamp: "2026-07-26T08:05:00Z" },
    { id: "log7", itemId: "inv3", itemName: "Emergency Tarpaulins", change: 8, reason: "Adjustment", user: "Fatima Begum", timestamp: "2026-07-25T16:20:00Z" },
    { id: "log8", itemId: "inv2", itemName: "Oral Rehydration Salts", change: 100, reason: "Restocking", user: "Mizanur Rahman", timestamp: "2026-07-25T14:35:00Z" },
    { id: "log9", itemId: "inv6", itemName: "First Aid Kits", change: -6, reason: "Distribution", user: "Taslima Khatun", timestamp: "2026-07-25T11:15:00Z" },
    { id: "log10", itemId: "inv5", itemName: "Portable Water Pumps", change: -1, reason: "Damage", user: "Mizanur Rahman", timestamp: "2026-07-24T17:05:00Z" },
  ],
  mapPins: [],
  syncQueue: [],
};
